# Generated by Django 4.0.4 on 2022-04-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_emp_adress_alter_emp_city_alter_emp_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
