# Generated by Django 4.0.4 on 2022-04-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_emp_dob_alter_emp_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='my_field',
            field=models.BooleanField(default=True),
        ),
    ]
